export const UI_TEXT = {
  nav: {
    home: 'HOME',
    work: 'WORK',
    sketchBook: 'SKETCH BOOK',
    laboratory: 'LABORATORY',
    info: 'INFO',
  },
  button: {
    english: 'ENGLISH',
    japanese: 'JAPANESE',
    code: 'CODE',
    back: 'BACK',
    settings: 'SETTINGS',
    menu: 'MENU',
    website: 'WEBSITE',
    application: 'APPLICATION',
    contact: 'CONTACT',
    save: 'SAVE',
    load: 'LOAD',
    export: 'EXPORT',
    import: 'IMPORT',
    applySettings: 'APPLY SETTINGS',
    close: 'CLOSE',
    withoutSaving: 'WITHOUT SAVING',
    cancel: 'CANCEL',
  },
  page: {
    myName: 'ACHA IKEDA',
    profession: 'DESIGNER & DEVELOPER',
    workSubtitle: 'SHOWING WEB APPLICATIONS',
    sketchBookSubtitle: 'SHOWING GENERATIVE ARTS',
    laboratorySubtitle: 'SHOWING EXPERIMENTAL WORKS',
  },
  settingItems: {
    centerColor: 'Center Color',
    middleColor: 'Middle Color',
    edgeColor: 'Edge Color',
    areaRadius: 'Area Radius',
    activeOvules: 'Active Ovules',
    ovuleSize: 'Ovule Size',
  },
} as const;

export const LANGUAGE = {
  english: 'English',
  japanese: 'Japanese',
  enToJa: 'English to Japanese',
  jaToEn: 'Japanese to English',
} as const;
